name: Compile LaTeX
on:
  push:
    paths:
      - '**.tex'
      
jobs:
  container:
    runs-on: ubuntu-latest
    container: kjarosh/latex:2024.4
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build using latexmk
        run: latexmk -pdf -output-directory=out latex/default.tex

      - name: List
        run: ls -la

      - name: Upload document
        run: |
          git add out/default.pdf
          git commit -m "Uploaded latest resume version"
          git push