name: Compile LaTeX
on:
  push:
    paths:
      - '**.tex'
  workflow_dispatch:

jobs:
  latex-build:
    runs-on: ubuntu-latest
    steps:
     # Docker layer caching
      - name: Enable Docker Layer Caching
        uses: satackey/action-docker-layer-caching@v0.0.11
        continue-on-error: true

      - name: Pull LaTeX Docker Image
        run: docker pull kjarosh/latex:2024.4

      - name: Checkout Source Files
        uses: actions/checkout@v4

      - name: Run LaTeX Build Inside Docker
        run: |
          docker run --rm \
            -v ${{ github.workspace }}:/workspace \
            -w /workspace \
            kjarosh/latex:2024.4 \
            latexmk -pdf -output-directory=out latex/default.tex
            
      - name: Upload document
        uses: actions/upload-artifact@v4
        with:
          name: compiled-pdf
          path: out/default.pdf
          
  upload-resume:
    needs: latex-build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: compiled-pdf
          
      - name: List
        run: ls
        
      - name: Upload pdf to github
        uses: EndBug/add-and-commit@v9
        with:
          add: "default.pdf"
          message: "Upload latest resume pdf"
    
  
         
